experiment_name: 'knife'
checkpoint_path: 'models/knife/checkpoints/model_epoch_0080.pth'
num_instances: 300
latent_dim: 128
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 1
hyper_hidden_features: 256

