batch_size: 20
epochs: 90
epochs_til_checkpoint: 5
expand: -1
experiment_name: bottle
hidden_num: 128
latent_dim: 128
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 5
loss_grad_temp: 100.0
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 300
on_surface_points: 4000
point_cloud_path: ../datasets/bottle/surface_pts_n_normal
steps_til_summary: 100
train_split: split/train/bottle.txt
