batch_size: 1
epochs: 10
epochs_til_checkpoint: 5
eval_split: split/eval/knife.txt
checkpoint_path: 'models/knife/checkpoints/model_epoch_0080.pth'
experiment_name: knife
hidden_num: 128
latent_dim: 128
logging_root: ./eval
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 300
on_surface_points: 4000
point_cloud_path: ../datasets/knife/surface_pts_n_normal
steps_til_summary: 90
